name: Deploy

on:
  push:
    branches: [ main, dev ]

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy DEV a EC2 Jose
        uses: appleboy/ssh-action@master
        with:
          host: gpstracker3.ddns.net
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: /home/ubuntu/deploy-dev.sh

  deploy-jose:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy EC2 Jose
        uses: appleboy/ssh-action@master
        with:
          host: gpstracker3.ddns.net
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: /home/ubuntu/deploy.sh

  deploy-daniel:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy EC2 Daniel
        uses: appleboy/ssh-action@master
        with:
          host: henriquezd.ddns.net
          username: ubuntu
          key: ${{ secrets.EC2_KEY_DANIEL }}
          script: /home/ubuntu/deploy.sh

  deploy-polo:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy EC2 Polo
        uses: appleboy/ssh-action@master
        with:
          host: gps-tracker.ddns.net
          username: ubuntu
          key: ${{ secrets.EC2_KEY_POLO }}
          script: /home/ubuntu/deploy.sh

  deploy-ivan:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy EC2 Ivan
        uses: appleboy/ssh-action@master
        with:
          host: barriosun.ddns.net
          username: ubuntu
          key: ${{ secrets.EC2_KEY_IVAN }}
          script: /home/ubuntu/deploy.sh